import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <div className="card1">
  <div className="card-border-top1">
  </div>
  <div className="img1">
   <img  className="img2" src="https://raw.githubusercontent.com/ayazmirza54/text-code-util.aiprod/main/client/public/assets/robot.png"></img>
  </div>
  <h2 className="job1">AI.shop Text,Code,Image and Video Utilities app</h2>
  <button className={styles.description}>Take a look at live version
  </button>
</div>
          
        </div>

        

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Buy AI projects <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Text and Code utils AI app
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Buy AI image tools <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              AI image tools
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              By AI Video tools <span>-&gt;</span>
            </h2>
           
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Buy AI Bundle consisting all apps <span>-&gt;</span>
            </h2>
            
          </a>
        </div>
        
      </main>
    </>
  )
}
